sudo: required
services: 
  - docker

before_install:
  - docker build -t kaganberk/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run  -e CI=true kaganberk/react-test npm test 

after_success:
  - docker build -t kaganberk/multi-client ./client
  - docker build -t kaganberk/multi-nginx ./nginx
  - docker build -t kaganberk/multi-server ./server
  - docker build -t kaganberk/multi-worker ./worker
 # log in docker
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_ID" --password-stdin
  #take those images and push tehm to docker hub
  - docker push kaganberk/multi-client
  - docker push kaganberk/multi-nginx
  - docker push kaganberk/multi-server
  - docker push kaganberk/multi-worker